name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python-version: "3.6"
            django-version: "1.11"
          - python-version: "3.7"
            django-version: "1.11"
          - python-version: "3.6"
            django-version: "2.2"
          - python-version: "3.7"
            django-version: "2.2"
          - python-version: "3.8"
            django-version: "3.2"
          - python-version: "3.9"
            django-version: "3.2"
          - python-version: "3.10"
            django-version: "3.2"
          - python-version: "3.11"
            django-version: "3.2"
          - python-version: "3.8"
            django-version: "4.0"
          - python-version: "3.9"
            django-version: "4.0"
          - python-version: "3.10"
            django-version: "4.0"
          - python-version: "3.11"
            django-version: "4.0"
          - python-version: "3.8"
            django-version: "4.1"
          - python-version: "3.9"
            django-version: "4.1"
          - python-version: "3.10"
            django-version: "4.1"
          - python-version: "3.11"
            django-version: "4.1"
      fail-fast: false

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django==${{ matrix.django-version }}
        pip install -e .[test]
        pip install pytest pytest-django

    - name: Run tests
      run: |
        pytest tests/*